### ISSUE TITLE
No modules named 'click'

### ISSUE THREAD

**Issue by kjeremy** [deathbeds/expectorate#4]
python 3.8.5 Windows x64

> $ expectorate -help
Traceback (most recent call last):
  File "C:\Users\jkolb\AppData\Local\Programs\Python\Python38\Scripts\expectorate-script.py", line 11, in <module>
    load_entry_point('expectorate', 'console_scripts', 'expectorate')()
  File "C:\Users\jkolb\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\jkolb\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "C:\Users\jkolb\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2462, in load
    return self.resolve()
  File "C:\Users\jkolb\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\projects\test\expectorate\src\expectorate\cli.py", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'

**Comment by bollwyvl** [comment]
Thanks for looking!

It's still very much a work in progress... At present some deps are only
captured at the conda level. Also hasn't been tested on windows.
